### ISSUE TITLE
Error when closing connection

### ISSUE THREAD

**Issue by qkaiser** [QKaiser/cottontail#24]
Currently getting this when closing a BlockingConnection implemented with SelectConnection:

```
2018-01-22 20:57:09 ERROR An exception occured: 'NoneType' object has no attribute 'poll'
Traceback (most recent call last):
  File "./bin/cottontail", line 253, in subproc
    channel.start_consuming()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1780, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 707, in process_data_events
    self._flush_output(common_terminator)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 455, in _flush_output
    self._impl.ioloop.poll()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 245, in poll
    self._poller.poll()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 923, in poll
    events = self._poll.poll(self._get_next_deadline())
AttributeError: 'NoneType' object has no attribute 'poll'
```

`_poll` attribute is not set in our SelectConnection for some reason :(

**Comment by qkaiser** [comment]
Slightly different exception in Python 3, same issue:

```
2018-01-22 21:09:48 ERROR An exception occured: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "./bin/cottontail", line 253, in subproc
    channel.start_consuming()
  File "/usr/local/lib/python3.5/dist-packages/pika/adapters/blocking_connection.py", line 1780, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python3.5/dist-packages/pika/adapters/blocking_connection.py", line 707, in process_data_events
    self._flush_output(common_terminator)
  File "/usr/local/lib/python3.5/dist-packages/pika/adapters/blocking_connection.py", line 455, in _flush_output
    self._impl.ioloop.poll()
  File "/usr/local/lib/python3.5/dist-packages/pika/adapters/select_connection.py", line 245, in poll
    self._poller.poll()
  File "/usr/local/lib/python3.5/dist-packages/pika/adapters/select_connection.py", line 923, in poll
    events = self._poll.poll(self._get_next_deadline())
OSError: [Errno 9] Bad file descriptor
```
